baseURL = "https://KenzyTran.github.io/aws-vprofile-gitops/"
title = "vProfile GitOps Workshop"
theme = "hugo-theme-learn"

defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = true

[languages]
  [languages.vi]
    languageName = "Tiếng Việt"
    contentDir = "content/vi"
    weight = 1
    languageCode = "vi"
    title = "vProfile GitOps Workshop"
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    weight = 2
    languageCode = "en"
    title = "vProfile GitOps Workshop"

[params]
  description = "Triển khai ứng dụng multi-tier vProfile lên AWS EKS theo mô hình GitOps với GitHub Actions và ArgoCD"
  author = "KenzyTran"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = true
  themeVariant = "workshop"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
